package com.ujiuye.mis.pojo;

import java.util.List;

public class Sources {


    private Boolean checked = false;

    public Boolean getChecked() {
        return checked;
    }

    public void setChecked(Boolean checked) {
        this.checked = checked;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sources.id
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sources.name
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sources.url
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sources.remark
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sources.pid
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sources.icon
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    private String icon;

    private List<Sources> children;

    public List<Sources> getChildren() {
        return children;
    }

    public void setChildren(List<Sources> children) {
        this.children = children;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sources.id
     *
     * @return the value of sources.id
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    public Integer getId() {
        return id;
    }




    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sources.id
     *
     * @param id the value for sources.id
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sources.name
     *
     * @return the value of sources.name
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sources.name
     *
     * @param name the value for sources.name
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sources.url
     *
     * @return the value of sources.url
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sources.url
     *
     * @param url the value for sources.url
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sources.remark
     *
     * @return the value of sources.remark
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sources.remark
     *
     * @param remark the value for sources.remark
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sources.pid
     *
     * @return the value of sources.pid
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sources.pid
     *
     * @param pid the value for sources.pid
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sources.icon
     *
     * @return the value of sources.icon
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sources.icon
     *
     * @param icon the value for sources.icon
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }
}