package com.ujiuye.mis.mapper;

import com.ujiuye.mis.pojo.RoleSources;
import com.ujiuye.mis.pojo.RoleSourcesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleSourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    long countByExample(RoleSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int deleteByExample(RoleSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int deleteByPrimaryKey(Integer rsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int insert(RoleSources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int insertSelective(RoleSources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    List<RoleSources> selectByExample(RoleSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    RoleSources selectByPrimaryKey(Integer rsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") RoleSources record, @Param("example") RoleSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int updateByExample(@Param("record") RoleSources record, @Param("example") RoleSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int updateByPrimaryKeySelective(RoleSources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int updateByPrimaryKey(RoleSources record);
}