package com.ujiuye.mis.mapper;

import com.ujiuye.mis.pojo.Sources;
import com.ujiuye.mis.pojo.SourcesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    long countByExample(SourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int deleteByExample(SourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int insert(Sources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int insertSelective(Sources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    List<Sources> selectByExample(SourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    Sources selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") Sources record, @Param("example") SourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int updateByExample(@Param("record") Sources record, @Param("example") SourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int updateByPrimaryKeySelective(Sources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Tue Aug 25 19:47:38 CST 2020
     */
    int updateByPrimaryKey(Sources record);

     List<Sources>  findAll2();
}